Lab 8 Problems

List of Imports

In [934]:
import numpy as np

Problem 1

In [935]:
a = np.array([1, 2, 3, 4, 5])

print(a)

[1 2 3 4 5]


Problem 2

In [936]:
def what(n):
    a = np.array([1, 2, 3, 4, 5], ndmin=n)
    print(a.ndim)
    return a

print(what(1))
print(what(2))
print(what(3))

# What is the difference between what(1), what(2) and what(3)?
# The n in what() is how many dimensions the output will be so what(1) is one dimension, what(2) is 2 dimensions and so on.

# what() transforms the array into n dimensions

1
[1 2 3 4 5]
2
[[1 2 3 4 5]]
3
[[[1 2 3 4 5]]]


Problem 3

In [937]:
a = np.array([1, 2, 3, 4], ndmin = 2 )
print(a) # should print [[1 2 3 4]]

[[1 2 3 4]]


Problem 4

In [938]:
a = np.array([1, 2, 3, 4])
print(a.ndim) # should print 1 (must refer to a)

b = np.array([[1, 2], [3, 4]])
print(a[0]) # should print 2 (must refer to b)

1
1


Problem 5

In [939]:
a = np.array([1, 2, 3, 4])
print(a[0]) # should print 1 must use a

1


Problem 6

In [940]:
a = np.array([10, 20, 30, 40, 50])
print(a[4]) # should print 50 must use a

50


Problem 7

In [941]:
a = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
print(a[1][0]) # should print 50 must use a

50


Problem 8

In [942]:
a = np.array([10, 20, 30, 40, 50])
print(a[-1]) # should print 50 must use a

50


Problem 9

In [943]:
a = np.array([10, 15, 20, 25, 30, 35, 40])
print(a[1:4]) # should print [15 20 25] must use a

[15 20 25]


Problem 10

In [944]:
a = np.array([10, 15, 20, 25, 30, 35, 40])
print(a[2:4]) # should print [20 25] must use a

[20 25]


Problem 11

In [945]:
a = np.array([10, 15, 20, 25, 30, 35, 40])
print(a[1:4:2]) # should print [15 25] must use a

[15 25]


Problem 12

In [946]:
a = np.array([10, 15, 20, 25, 30, 35, 40])
print(a[::2]) # should print [10 20 30 40] must use a

[10 20 30 40]


Problem 13

In [947]:
a = np.array([1, 2, 3])
print(a.dtype) # should print something indicating this is an array of integers

int64


Problem 14

In [948]:
a = np.array([1, 2, 3, 4], dtype= str )

# Then predict and explain the output for the following expressions
# The first print() prints the data type of the a which is <U1
# The second print() prints the concatenation of the strings of "1" and "2" and outputs 12.
# The third print() prints the addition of ints from b which is a int form of a which is 5+1+3 which is 9.
# The last print() prints the concatenation of the strings "5", "1", and "3" and outputs '513'. 

print(a.dtype)
print(a[0] + a[1])
a = np.array([5, 1, -1, 3], dtype='S')
b = a.astype('i') # what happens here? 
# This changes the items in the array into int type from str type
print(b[0] + b[1] + b[3]) 
print(a[0] + a[1] + a[3])

<U1
12
9
b'513'


Problem 15

In [949]:
a = np.array([1.1, 2.1, 3.1])
b = a.astype(int)
print(b) # should print [1 2 3] now 

[1 2 3]


Problem 16

In [950]:
a = np.array([1, 2, 3, 4, 5])
x = np.copy(a) # must use a to make a copy of it 

# Then predict the effect of the following expressions
# x[0] = -5 does not change the array a because it is changing the copy of a assigned to x which would be different from a if printed.
# b[0] = -25 does change the a[0] element from 1 to 25 because b = a is not assigning a copy, it is assigning the original array.

x[0] = -5
print(a) # does a see the change? 
b = a
b[0] = -25
print(a) # does a see the change? 

[1 2 3 4 5]
[-25   2   3   4   5]


Problem 17

In [951]:
a = np.array([1, 2, 3, 4, 5])
d = a.view()

# Then predict the effect of these expressions:
# a.base evaluates if a is based on a previous variable so it will print None because it is not based on another variable.
# d.base evaluates if d is based on a previous variable so it will print [1,2,3,4,5] because it is based on the variable a.


print(a.base)
print(d.base) # why is this different from all the others?
b = a
print(b.base)
c = a.copy()
print(c.base)

None
[1 2 3 4 5]
None
None


Problem 18

In [952]:
a = np.array([1, 2, 3, 4])
print(a.shape)

a = a.reshape(1, 4)
print(a)

a = a.reshape(2, 2)
print(a)

a = a.reshape(4, 1)
print(a)

(4,)
[[1 2 3 4]]
[[1 2]
 [3 4]]
[[1]
 [2]
 [3]
 [4]]


Problem 19

In [953]:
a = np.array([1, 2, 3, 4])
a = a.reshape(2,2) # write code here must use a
print(a) # must print [[1, 2] [3 4]]

#     now predict and explain the output of these expressions 

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
b = a.reshape(4, 3)
print(b)
b = a.reshape(3, 4)
print(b)

[[1 2]
 [3 4]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Problem 20

In [954]:
a = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
b = a.reshape(-1) # complete this statement to result in the output below
print(b) # must print [ 1  2  3  4  5  6  7  8  9 10 11 12]

[ 1  2  3  4  5  6  7  8  9 10 11 12]


Problem 21

In [955]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate((a,b)) # use np, a and b somehow 
print(c) # must print [1 2 3 4 5 6]

#     then predict and explain the outcome of the following expressions

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.concatenate((a, b), axis=1) # what is the effect of the second parameter? 
print(c) # what gets printed and why? 
c  = np.stack((a, b), axis = 0) # what does stack do differently (if anything)? 
print(c) # what gets printed and why?

[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Problem 22

In [956]:
a = np.array([1, 2, 3, 4, 5, 4, 4])
where = np.where(a==4) # complete statement, must use np, a and 4
print(where) # must print (array([3, 5, 6]),)

(array([3, 5, 6]),)


Problem 23

In [957]:
a = np.array([3, 2, 0, 1])
b = np.sort(a) # complete statement, must use np and a
print(b) # must print [0 1 2 3]

[0 1 2 3]


Problem 24

In [958]:
# write your solution here

## Data: yearly salary in ($1000) [2017, 2018, 2019]
alice = [99, 101, 103]
bob = [110, 108, 105]
tim = [90, 88, 85]
salaries = np.array([alice, bob, tim])
taxation = np.array([[0.2, 0.25, 0.22],
 [0.4, 0.5, 0.5],
 [0.1, 0.2, 0.1]])

## One-liner
max_income = np.max(salaries - salaries * taxation)

name_index = ['alice', 'bob', 'tim']
incomes_after_tax = (salaries - salaries * taxation)
# max_income
index = np.nonzero(incomes_after_tax == max_income)
print(name_index[index[0][0]])


tim


Problem 25

In [959]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(np.average(a, axis=0)) # review the meaning of the axis parameter
print(np.average(a, axis=1))
print(np.average(a, axis=2))


[[3. 4.]
 [5. 6.]]
[[2. 3.]
 [6. 7.]]
[[1.5 3.5]
 [5.5 7.5]]


Problem 26

In [960]:
a = np.array([[[ 1,  2,  3], [22,  5,  6], [ 7,  8,  9]],
              [[11, 12, 10], [ 4, 14, 15], [16, 17, 18]],
              [[19, 20, 21], [13, 23, 24], [25, 26, 27]]])

b = np.sort(a, axis=0)
print(b) # what gets printed and why?
# The output below is printed is sorted by column smallest to largest going down the column.

c = np.sort(a, axis=1)
print(c)
d = np.sort(a, axis=2)
print(d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 10]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2  3]
  [ 7  5  6]
  [22  8  9]]

 [[ 4 12 10]
  [11 14 15]
  [16 17 18]]

 [[13 20 21]
  [19 23 24]
  [25 26 27]]]
[[[ 1  2  3]
  [ 5  6 22]
  [ 7  8  9]]

 [[10 11 12]
  [ 4 14 15]
  [16 17 18]]

 [[19 20 21]
  [13 23 24]
  [25 26 27]]]
